apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: m1m2g66wl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: m1m2g66wl-nodejs 
  name: m1m2g66wl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: m1m2g66wl-nodejs 
